export const Strings = {
  common: {
    loading: "Loading...",
    signOut: "Sign out",
    signingOut: "Signing out...",
    cancel: "Cancel",
    confirm: "Confirm",
    delete: "Delete",
    retry: "Try again",
    comingSoon: "Coming soon",
    comingSoonDescription:
      "We're putting the finishing touches on this feature. Check back soon for updates.",
    backToHome: "Back to home",
    save: "Save changes",
  },
  portal: {
    brandName: "Tender Paws",
    brandTagline: "Vendor Portal",
    openMenu: "Open menu",
    closeMenu: "Close menu",
    openProfile: "Open profile",
    goBack: "Go back",
  },
  nav: {
    dashboard: "Dashboard",
    products: "Products",
    orders: "Orders",
    earnings: "Earnings",
    settings: "Settings",
    logOut: "Log out",
    lockedHint: "Available after admin approval",
  },
  pages: {
    dashboard: {
      title: "Dashboard",
      subtitle: "Your store overview",
    },
    profile: {
      title: "Profile",
      subtitle: "Store details, account status, and change requests",
    },
    products: {
      title: "Products",
      subtitle: "Catalog, stock, and product status",
      newTitle: "Add product",
      newSubtitle: "Create a new item for your store catalog",
      editTitle: "Edit product",
      editSubtitle: "Update details, pricing, stock, and images",
    },
    orders: {
      title: "Orders",
      subtitle: "Your store orders only",
    },
    earnings: {
      title: "Earnings",
      subtitle: "Sales, commission, and payouts",
    },
    settings: {
      title: "Settings",
      subtitle: "Appearance and language preferences",
    },
    notifications: {
      title: "Notifications",
      subtitle: "Orders, account updates, and store alerts",
    },
  },
  accountStatus: {
    title: "Your application",
    activeTitle: "Store activated",
    activeMessage:
      "Your vendor account is active. You can manage products, orders, and earnings from the portal.",
    pendingMessage: "Your vendor application is pending admin review.",
    pendingBannerTitle: "Pending admin activation",
    pendingBannerMessage:
      "Your store profile was submitted. You cannot publish products until approved.",
    suspendedProductsMessage:
      "You cannot access products, orders, or earnings while your account is suspended.",
    pendingProductsMessage:
      "You will be able to access products and orders once an admin approves your application in the Tender Paws admin panel.",
    store: "Store",
    email: "Email",
    status: "Status",
    reason: "Reason",
    accessRestored: "Access restored",
    contactSupport: "Contact support",
    suspended: "suspended",
    pending: "pending",
    active: "active",
  },
  profile: {
    currentProfileTitle: "Current profile",
    requestChangesTitle: "Request store info changes",
    requestChangesHint:
      "Updates are reviewed by the Tender Paws admin team before they go live.",
    signInEmailNote: "Sign-in email cannot be changed here. Contact support if needed.",
    uploadLogo: "Click to upload a new logo",
    noLogo: "No logo",
    submitChangeRequest: "Submit change request",
    submittingChangeRequest: "Submitting...",
    changeRequestSuccess:
      "Change request submitted. An admin will review your updated store information.",
    changeRequestError: "Could not submit your change request. Please try again.",
    pendingChangeExists:
      "You already have a pending change request. Wait for admin review before submitting another.",
    pendingChangeBanner:
      "A profile change request is pending admin review. You will be notified once it is processed.",
    fields: {
      ownerName: "Owner full name",
      signInEmail: "Sign-in email",
      phone: "Mobile phone",
      storeName: "Store name",
      storeDescription: "Store description",
      contactPhone: "Contact phone",
      contactEmail: "Store contact email",
      contactAddress: "Business address",
      logo: "Store logo",
      updatedAt: "Last updated",
    },
    validation: {
      ownerName: "Owner name is required.",
      phone: "Mobile phone is required.",
      storeName: "Store name is required.",
      storeDescription: "Store description is required.",
      contactPhone: "Contact phone is required.",
      contactEmail: "Store contact email is required.",
      contactAddress: "Business address is required.",
    },
  },
  signOut: {
    confirmTitle: "Sign out?",
    confirmMessage:
      "You'll be signed out of your current session. Any unsaved changes may be lost.",
    confirmAction: "Yes, sign out",
  },
  session: {
    title: "Active session",
    device: "Device",
    signedIn: "Signed in",
    lastLogin: "Last login",
    accountCreated: "Account created",
    location: "Location",
  },
  notifications: {
    open: "Open notifications",
    unreadSummaryZero: "You have no unread notifications",
    unreadSummaryOne: "You have 1 unread notification",
    unreadSummaryMany: "You have {count} unread notifications",
    markAllAsRead: "Mark all as read",
    markAllBusy: "Please wait…",
    tabAll: "All",
    tabUnread: "Unread",
    emptyAllTitle: "No notifications",
    emptyUnreadTitle: "No unread notifications",
    emptySubtitle: "You're all caught up.",
    loading: "Loading notifications…",
  },
  settings: {
    appearanceTitle: "Appearance",
    themeLabel: "Theme",
    themeLight: "Light",
    themeDark: "Dark",
    languageTitle: "Language",
    languageLabel: "Display language",
    languageEnglish: "English",
    languageArabic: "Arabic",
    savedHint: "Preferences are saved on this device.",
  },
  errors: {
    generic: "Something went wrong. Please try again.",
    unauthorized: "You don't have permission to view this page.",
    forbidden: "This action is not allowed for your account.",
    notFound: "Page not found.",
    networkError: "Unable to connect. Check your internet and try again.",
    validationRequired: "This field is required.",
    validationEmail: "Please enter a valid email address.",
  },
  products: {
    phaseBadge: "Products",
    addProduct: "Add product",
    editProduct: "Edit product",
    searchPlaceholder: "Search products…",
    filterStatus: "Filter by status",
    filterCategory: "Filter by category",
    filterAllStatuses: "All statuses",
    filterAllCategories: "All categories",
    filterLabel: "Filter",
    filterTitle: "Filter products",
    filteringBy: "Filtering by",
    filterNoSelection: "All products — no filters applied yet",
    applyFilters: "Apply filters",
    applyFiltersWithCount: "Apply filters ({count})",
    resetFilters: "Reset filters",
    tableProduct: "Product",
    tableCategory: "Category",
    tablePrice: "Price",
    tableStock: "Stock",
    tableStatus: "Status",
    tableActions: "Actions",
    emptyTitle: "No products yet",
    emptyDescription:
      "Add your first product to start selling through the Tender Paws mobile app.",
    emptyFilteredTitle: "No matching products",
    emptyFilteredDescription: "Try adjusting your search or filters.",
    clearFilters: "Clear filters",
    loadError: "We couldn't load your products. Please try again.",
    saveError: "We couldn't save this product. Please try again.",
    deleteError: "We couldn't remove this product. Please try again.",
    createSuccess: "Product added to your catalog.",
    updateSuccess: "Product updated successfully.",
    deleteSuccess: "Product removed from your catalog.",
    deleteTitle: "Remove product?",
    deleteMessage:
      "This product will be hidden from buyers. You can add a new listing later if needed.",
    deleteConfirm: "Remove product",
    deleting: "Removing…",
    saving: "Saving…",
    saveProduct: "Save product",
    cancelEdit: "Cancel",
    editAction: "Edit product",
    deleteAction: "Remove product",
    uploadImages: "Add images",
    uploadImagesHint: "Upload up to 8 images. The first image is shown in search results.",
    setPrimaryImage: "Set as cover",
    primaryImage: "Cover",
    fields: {
      name: "Product name",
      description: "Description",
      category: "Category",
      price: "Price (EGP)",
      stock: "Stock quantity",
      status: "Status",
      sku: "SKU (optional)",
    },
    placeholders: {
      name: "e.g. Dry Food 10kg",
      description: "Describe ingredients, size, or what makes this product special.",
      sku: "Internal reference code",
    },
    statusLabels: {
      active: "Active",
      inactive: "Inactive",
      out_of_stock: "Out of stock",
      archived: "Archived",
    },
    stockLow: "{count} left",
    export: {
      label: "Export",
      title: "Export products",
      subtitle: "Choose which columns to include in your CSV download.",
      action: "Download CSV",
      noData: "There are no products to export. Adjust search or filters and try again.",
    },
    tabsLabel: "Products sections",
    tabs: {
      catalog: "Catalog",
      categories: "Categories",
    },
    categories: {
      badge: "Categories",
      title: "Platform categories",
      subtitle:
        "Activate or deactivate categories buyers can browse. Inactive categories are hidden when adding products.",
      tableName: "Category",
      tableStatus: "Status",
      tableActions: "Actions",
      activate: "Activate",
      deactivate: "Deactivate",
      activateSuccess: "{name} is now active for new products.",
      deactivateSuccess: "{name} is now inactive and hidden from new listings.",
      loadError: "We couldn't load categories. Please try again.",
      updateError: "We couldn't update this category. Please try again.",
      emptyTitle: "No categories found",
      emptyDescription: "Platform categories will appear here once configured.",
    },
    validation: {
      name: "Product name is required.",
      category: "Select a category.",
      price: "Enter a valid price.",
      stock: "Enter a valid stock quantity.",
      images: "Add at least one product image.",
      descriptionLength: "Description is too long.",
    },
  },
} as const;
